### ISSUE TITLE
Checkbox component

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/WebBlocks#8]
Everybody knows that it can be a bit hard to line up a custem checkbox as you want it to be.
This component should make that easier.
It should be a funny one which should work with emojis.

The component itself should accept to props. A check-true and check-false prop where you can pass emojis for the two states a checkbox could have.

It should also accept content via a slot.

**Comment by ruffle1986** [comment]
Could you please explain what do you mean by `It should also accept content via a slot.`

**Comment by r4pt0s** [comment]
Sure @ruffle1986.
A checkbox usually has a text label on the right side.

With web components you have the ability to pass content via a slot name to the web component and render it there where you want to.

**Comment by ruffle1986** [comment]
Ah I see, this one https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot

**Comment by r4pt0s** [comment]
@ruffle1986
Do you work on it?

**Comment by OPerel** [comment]
Hey @r4pt0s 
I would like to give it a shot

**Comment by r4pt0s** [comment]
@OPerel
Go for it 💪🏻

**Comment by OPerel** [comment]
Hello @r4pt0s and @IM-Deane (and everyone else),
I would like to discuss some options for implementing this component.
Using emojis in HTML poses some layout and style challenges due to several reasons:
- The wide range of emojis the user can potentially select.
- Emojis may be rendered quite differently by different browsers.
- The user may want to pass in custom styles that will affect the original style in unpredictable ways.

In order to face these issues I want to make the component highly customizable. And I would love your input on two options for implementing the component's API to allow customization.
1. The first may be called the props pattern. I.e. to expose styling options for the different parts of the component via props. Something like so:
```tsx
<checkbox-component
  checkTrue="\2714"
  checkFalse="\2716"
  checkmarkStyles={{ /* jsx style object */ }}
  labelStyles={{ /* jsx style object */ }}
  // ...otherProps
>
  Checkbox Label
</checkbox-component>
```

2. The other option may be called compound components pattern, i.e. exposing the API as different components the user can use and style the way he likes:
```tsx
<checkbox-component
  checkTrue="\2714"
  checkFalse="\2716"
  // ...otherProps
>
  <label-component class="some-class">
    Checkbox Label
  </label-component>
  <checkmark-emoji-component
    checkTrue={this.checkTrue}
    checkFalse={this.checkFalse}
    class="some-other-class"
  />
</checkbox-component>
```

If you have any other ideas I would to hear them.
I tend to go with the second option, because I like the possibility of changing the order of the inner components.
Thanks a lot 🙏

**Comment by r4pt0s** [comment]
@OPerel
The second one also makes more sense for me personally.
I like the thought process 👏🏻👏🏻

**Comment by software-trizzey** [comment]
@OPerel I love the analytical approach to this!

I also agree with the second approach as I think it would make the component more flexible.
